### ISSUE TITLE
Play integrity check fails OnePlus 5T

### ISSUE THREAD

**Issue by CYBEROG08** [Seshiria/op5dc#3]
![IMG_20231004_223549](https://github.com/Seshiria/op5dc/assets/94737640/deb28d11-49ff-4169-8a5e-675f2f286f3a)
![Screenshot_20231003-203216_Yet Another SafetyNet Attestation Checker](https://github.com/Seshiria/op5dc/assets/94737640/5275e3be-b589-4b54-9c5c-a67d78333141)

![Screenshot_20231003-203223_Play Integrity API Checker](https://github.com/Seshiria/op5dc/assets/94737640/a02e1535-619e-438f-a4c3-0f2680d2c1b2)

Safetynet check pass but play integrity fails what's the issue?

**Comment by Seshiria** [comment]
* First of all, based on your first screenshot it looks like you didn't succeed in flashing the .zip files.
Please check your phone :
``setting > about phone > android version > kernel version``


* Secondly "Safetynet check pass but play integrity fails what's the issue?"
This repo doesn't address such issues, and you don't need to be concerned about such issues if your app is working fine. :)
Suggest to refer to the repo:
https://github.com/kdrag0n/safetynet-fix
https://github.com/LSPosed/LSPosed.github.io/releases

**Comment by CYBEROG08** [comment]
![Screenshot_20231004-231546_Settings](https://github.com/Seshiria/op5dc/assets/94737640/96a028ac-0e65-4dda-927d-a0c0d1ba8266)
This is the kernal version

And without play integrity check I can't able to bypass to use the bank apps example like payzapp not showing in playstore some bank apps are showing rooted or jailbreak while safetynet check passed some apps are working fine some or not
With ur given repo I can sideload it it will work full for the play integrity check to pass ??

**Comment by Seshiria** [comment]
You didn't succeed in swiping the .zip file, don't worry, this looks like an issue with this repo, I'll fix that.:)

Regarding "play integrity api check" and "bypassing root", I can only suggest you to  try to use the above two repos, I can't make any guarantees.

**Comment by CYBEROG08** [comment]
> Regarding "play integrity api check" and "bypassing root", I can only suggest you to try to use the above two repos, I can't make any guarantees.

Can u share the steps and which 2 repo to sideload it
And this is for the OnePlus 5T device?

**Comment by CYBEROG08** [comment]
> You didn't succeed in swiping the .zip file, don't worry, this looks like an issue with this repo, I'll fix that.:)
> sure waiting for that....

**Comment by Seshiria** [comment]
* Can u share the steps and which 2 repo to sideload it
And this is for the OnePlus 5T device?

>This is a "generic" solution for all modern android devices, since I don't maintain a repo for it, you should find the repo and check their readme.
The short steps are:
You need to install [magisk ](https://github.com/topjohnwu/Magisk)first, and load "[safetynet-fix](https://github.com/kdrag0n/safetynet-fix)' using magisk's module function, which should fix showing in playstore.
Then load "[shamiko](https://github.com/LSPosed/LSPosed.github.io/releases)" and select the corresponding bank app, this should solve the problem that bank apps are showing rooted.

Note that I am not involved in the above repo


----------------------------------------------

I tried to fix the problem with flashing the .zip, please use this:
[op5lin20-dc-44302_testbuild_20231005-045322_45f6f.zip](https://github.com/Seshiria/op5dc/files/12812470/op5lin20-dc-44302_testbuild_20231005-045322_45f6f.zip)

**Comment by CYBEROG08** [comment]
> I tried to fix the problem with flashing the .zip, please use this: [op5lin20-dc-44302_testbuild_20231005-045322_45f6f.zip](https://github.com/Seshiria/op5dc/files/12812470/op5lin20-dc-44302_testbuild_20231005-045322_45f6f.zip)

Is that working module??  Or This is the new one

**Comment by CYBEROG08** [comment]
> > This is a "generic" solution for all modern android devices, since I don't maintain a repo for it, you should find the repo and check their readme.
> > The short steps are:
> > You need to install [magisk ](https://github.com/topjohnwu/Magisk)first, and load "[safetynet-fix](https://github.com/kdrag0n/safetynet-fix)' using magisk's module function, which should fix showing in playstore.
> > Then load "[shamiko](https://github.com/LSPosed/LSPosed.github.io/releases)" and select the corresponding bank app, this should solve the problem that bank apps are showing rooted.
> 
> Note that I am not involved in the above repo

 actually I used ih8sn module to fix the safetynet check that are passed but they mentioned play integrity also will pass while sideload
So for that I need to remove that kernal module first after that I need to use magisk and load the shamiko 
Is that right ??

**Comment by Seshiria** [comment]
> > I tried to fix the problem with flashing the .zip, please use this: [op5lin20-dc-44302_testbuild_20231005-045322_45f6f.zip](https://github.com/Seshiria/op5dc/files/12812470/op5lin20-dc-44302_testbuild_20231005-045322_45f6f.zip)
> > Is that working module??  Or This is the new one

This is the newly built kernel.zip of this repo which should solve the problem of being unable to flash.



> > > This is a "generic" solution for all modern android devices, since I don't maintain a repo for it, you should find the repo and check their readme.
> > > The short steps are:
> > > You need to install [magisk ](https://github.com/topjohnwu/Magisk)first, and load "[safetynet-fix](https://github.com/kdrag0n/safetynet-fix)' using magisk's module function, which should fix showing in playstore.
> > > Then load "[shamiko](https://github.com/LSPosed/LSPosed.github.io/releases)" and select the corresponding bank app, this should solve the problem that bank apps are showing rooted.
> > 
> > 
> > Note that I am not involved in the above repo
> 
> actually I used ih8sn module to fix the safetynet check that are passed but they mentioned play integrity also will pass while sideload So for that I need to remove that kernal module first after that I need to use magisk and load the shamiko Is that right ??

I have never used the ih8sn module, So I don't know, you can try it.:）

**Comment by CYBEROG08** [comment]
> > > I tried to fix the problem with flashing the .zip, please use this: [op5lin20-dc-44302_testbuild_20231005-045322_45f6f.zip](https://github.com/Seshiria/op5dc/files/12812470/op5lin20-dc-44302_testbuild_20231005-045322_45f6f.zip)
> > > Is that working module??  Or This is the new one
> 
> This is the newly built kernel.zip of this repo which should solve the problem of being unable to flash.
> 
> > > > This is a "generic" solution for all modern android devices, since I don't maintain a repo for it, you should find the repo and check their readme.
> > > > The short steps are:
> > > > You need to install [magisk ](https://github.com/topjohnwu/Magisk)first, and load "[safetynet-fix](https://github.com/kdrag0n/safetynet-fix)' using magisk's module function, which should fix showing in playstore.
> > > > Then load "[shamiko](https://github.com/LSPosed/LSPosed.github.io/releases)" and select the corresponding bank app, this should solve the problem that bank apps are showing rooted.
> > > 
> > > 
> > > Note that I am not involved in the above repo
> > 
> > 
> > actually I used ih8sn module to fix the safetynet check that are passed but they mentioned play integrity also will pass while sideload So for that I need to remove that kernal module first after that I need to use magisk and load the shamiko Is that right ??
> 
> I have never used the ih8sn module, So I don't know, you can try it.:）


And for the op5line20-dc testbuild I need to sideload via on adb same like gapps sideload or its mandatory to use magisk 
So after flash this module I need to reflash the mindgapps ??

May I know the proper steps to flash it cuz whenever I tried some of them are passed some are failed that's why I am asking

**Comment by Seshiria** [comment]
> > > > I tried to fix the problem with flashing the .zip, please use this: [op5lin20-dc-44302_testbuild_20231005-045322_45f6f.zip](https://github.com/Seshiria/op5dc/files/12812470/op5lin20-dc-44302_testbuild_20231005-045322_45f6f.zip)
> > > > Is that working module??  Or This is the new one
> > 
> > 
> > This is the newly built kernel.zip of this repo which should solve the problem of being unable to flash.
> > > > > This is a "generic" solution for all modern android devices, since I don't maintain a repo for it, you should find the repo and check their readme.
> > > > > The short steps are:
> > > > > You need to install [magisk ](https://github.com/topjohnwu/Magisk)first, and load "[safetynet-fix](https://github.com/kdrag0n/safetynet-fix)' using magisk's module function, which should fix showing in playstore.
> > > > > Then load "[shamiko](https://github.com/LSPosed/LSPosed.github.io/releases)" and select the corresponding bank app, this should solve the problem that bank apps are showing rooted.
> > > > 
> > > > 
> > > > Note that I am not involved in the above repo
> > > 
> > > 
> > > actually I used ih8sn module to fix the safetynet check that are passed but they mentioned play integrity also will pass while sideload So for that I need to remove that kernal module first after that I need to use magisk and load the shamiko Is that right ??
> > 
> > 
> > I have never used the ih8sn module, So I don't know, you can try it.:）
> 
> And for the op5line20-dc testbuild I need to sideload via on adb same like gapps sideload or its mandatory to use magisk So after flash this module I need to reflash the mindgapps ??
> 
> May I know the proper steps to flash it cuz whenever I tried some of them are passed some are failed that's why I am asking

Yes, adb sideload in recovery.Flashing op5lin20.zip will only affect /boot. In theory, there is no need to flash mindgapps again.

The general order of updating the system:
1,flash lineageos
2,flash gapps
3,Other(including op5lin_dc,magisk...)

**Comment by CYBEROG08** [comment]
> > > > > I tried to fix the problem with flashing the .zip, please use this: [op5lin20-dc-44302_testbuild_20231005-045322_45f6f.zip](https://github.com/Seshiria/op5dc/files/12812470/op5lin20-dc-44302_testbuild_20231005-045322_45f6f.zip)
> > > > > Is that working module??  Or This is the new one
> > > 
> > > 
> > > This is the newly built kernel.zip of this repo which should solve the problem of being unable to flash.
> > > > > > This is a "generic" solution for all modern android devices, since I don't maintain a repo for it, you should find the repo and check their readme.
> > > > > > The short steps are:
> > > > > > You need to install [magisk ](https://github.com/topjohnwu/Magisk)first, and load "[safetynet-fix](https://github.com/kdrag0n/safetynet-fix)' using magisk's module function, which should fix showing in playstore.
> > > > > > Then load "[shamiko](https://github.com/LSPosed/LSPosed.github.io/releases)" and select the corresponding bank app, this should solve the problem that bank apps are showing rooted.
> > > > > 
> > > > > 
> > > > > Note that I am not involved in the above repo
> > > > 
> > > > 
> > > > actually I used ih8sn module to fix the safetynet check that are passed but they mentioned play integrity also will pass while sideload So for that I need to remove that kernal module first after that I need to use magisk and load the shamiko Is that right ??
> > > 
> > > 
> > > I have never used the ih8sn module, So I don't know, you can try it.:）
> > 
> > 
> > And for the op5line20-dc testbuild I need to sideload via on adb same like gapps sideload or its mandatory to use magisk So after flash this module I need to reflash the mindgapps ??
> > May I know the proper steps to flash it cuz whenever I tried some of them are passed some are failed that's why I am asking
> 
> Yes, adb sideload in recovery.Flashing op5lin20.zip will only affect /boot. In theory, there is no need to flash mindgapps again.
> 
> The general order of updating the system: 1,flash lineageos 2,flash gapps 3,Other(including op5lin_dc,magisk...)



![IMG-20231005-WA0014](https://github.com/Seshiria/op5dc/assets/94737640/27b25edc-f306-456d-b86e-71e6a4f3d46c)


After flashing the zip file still facing the play integrity check failed and not showing payzapp and axis app in play Store whats the issue now??
Before & after flashing cleared play service and play Store data,cache

**Comment by Seshiria** [comment]
> After flashing the zip file still facing the play integrity check failed and not showing payzapp and axis app in play Store whats the issue now?? Before & after flashing cleared play service and play Store data,cache

Yes, you successfully flashed the .zip and have solved the problem with this repo. Please forgive me for using translation software, English is not my area of expert.

----------------------------------------

Regarding "play integrity api check" and "bypassing root",Please try using the following scheme, note that this issue is beyond the scope of this repo and can only be used as operational advice.

>You need to install [magisk ](https://github.com/topjohnwu/Magisk)first, and load "[safetynet-fix](https://github.com/kdrag0n/safetynet-fix)' using magisk's module function, which should fix showing in playstore.

>Then load "[shamiko](https://github.com/LSPosed/LSPosed.github.io/releases)" and select the corresponding bank app, this should solve the problem that bank apps are showing rooted.

**Comment by CYBEROG08** [comment]
> > After flashing the zip file still facing the play integrity check failed and not showing payzapp and axis app in play Store whats the issue now?? Before & after flashing cleared play service and play Store data,cache
> 
> Yes, you successfully flashed the .zip and have solved the problem with this repo. Please forgive me for using translation software, English is not my area of expert.
> 
> Regarding "play integrity api check" and "bypassing root",Please try using the following scheme, note that this issue is beyond the scope of this repo and can only be used as operational advice.
> 
> > You need to install [magisk ](https://github.com/topjohnwu/Magisk)first, and load "[safetynet-fix](https://github.com/kdrag0n/safetynet-fix)' using magisk's module function, which should fix showing in playstore.
> 
> > Then load "[shamiko](https://github.com/LSPosed/LSPosed.github.io/releases)" and select the corresponding bank app, this should solve the problem that bank apps are showing rooted.


Sure! 
But still now I didn't use the magisk
Seeing on other options 😕

**Comment by Seshiria** [comment]
> > > After flashing the zip file still facing the play integrity check failed and not showing payzapp and axis app in play Store whats the issue now?? Before & after flashing cleared play service and play Store data,cache
> > 
> > 
> > Yes, you successfully flashed the .zip and have solved the problem with this repo. Please forgive me for using translation software, English is not my area of expert.
> > Regarding "play integrity api check" and "bypassing root",Please try using the following scheme, note that this issue is beyond the scope of this repo and can only be used as operational advice.
> > > You need to install [magisk ](https://github.com/topjohnwu/Magisk)first, and load "[safetynet-fix](https://github.com/kdrag0n/safetynet-fix)' using magisk's module function, which should fix showing in playstore.
> > 
> > 
> > > Then load "[shamiko](https://github.com/LSPosed/LSPosed.github.io/releases)" and select the corresponding bank app, this should solve the problem that bank apps are showing rooted.
> 
> Sure! But still now I didn't use the magisk Seeing on other options 😕

What is the root you are currently using?

**Comment by CYBEROG08** [comment]
> > > > After flashing the zip file still facing the play integrity check failed and not showing payzapp and axis app in play Store whats the issue now?? Before & after flashing cleared play service and play Store data,cache
> > > 
> > > 
> > > Yes, you successfully flashed the .zip and have solved the problem with this repo. Please forgive me for using translation software, English is not my area of expert.
> > > Regarding "play integrity api check" and "bypassing root",Please try using the following scheme, note that this issue is beyond the scope of this repo and can only be used as operational advice.
> > > > You need to install [magisk ](https://github.com/topjohnwu/Magisk)first, and load "[safetynet-fix](https://github.com/kdrag0n/safetynet-fix)' using magisk's module function, which should fix showing in playstore.
> > > 
> > > 
> > > > Then load "[shamiko](https://github.com/LSPosed/LSPosed.github.io/releases)" and select the corresponding bank app, this should solve the problem that bank apps are showing rooted.
> > 
> > 
> > Sure! But still now I didn't use the magisk Seeing on other options 😕
> 
> What is the root you are currently using?


Sorry I can't get it

**Comment by Seshiria** [comment]
> Sorry I can't get it

What I would like to know is how did you get "root" privileges on your android device . For example, magisk,kernelsu...

Generally speaking, flashing lineageos alone will not cause "rooted or jailbreak" of bank apps, I can think of two points:
1, the lineageos system you flashed does not conform to the safe implementation, it may have modified some parts of the app to cause errors, or you modified some resources of lineageos.
2. the bank app is not just checking for play integrity or "root", he may have checked other things, such as files on your device, or your ip, etc.

I googled "payzapp" and found the following:
https://www.desidime.com/discussions/rooted-phone-users-do-not-update-payzapp

Someone mentioned:
>mine's not rooted and still shows that error - RIP

**Comment by CYBEROG08** [comment]
> > Sorry I can't get it
> 
> What I would like to know is how did you get "root" privileges on your android device . For example, magisk,kernelsu...
> 
> Generally speaking, flashing lineageos alone will not cause "rooted or jailbreak" of bank apps, I can think of two points: 1, the lineageos system you flashed does not conform to the safe implementation, it may have modified some parts of the app to cause errors, or you modified some resources of lineageos. 2. the bank app is not just checking for play integrity or "root", he may have checked other things, such as files on your device, or your ip, etc.
> 
> I googled "payzapp" and found the following: https://www.desidime.com/discussions/rooted-phone-users-do-not-update-payzapp
> 
> Someone mentioned:
> 
> > mine's not rooted and still shows that error - RIP


😃🥳Thanks for the help for the new build yesterday you have posted that helps me to bypass the root or jailbroke message from bank apps.....I using the lineage OS and kernalSU on first time using that installed the kernalSU it shows the root or jailbroke message yesterday I reflash with your new build and nikgapps used instead of mindgapps it's working......today the app is showing in Play Store (payzapp) but play integrity check (MEET_STRONG_INTEGRITY) is failed and in Play Store- device is not certified.....how the app is working I don't know 🤔🤔😅

**Comment by Seshiria** [comment]
> > > Sorry I can't get it
> > 
> > 
> > What I would like to know is how did you get "root" privileges on your android device . For example, magisk,kernelsu...
> > Generally speaking, flashing lineageos alone will not cause "rooted or jailbreak" of bank apps, I can think of two points: 1, the lineageos system you flashed does not conform to the safe implementation, it may have modified some parts of the app to cause errors, or you modified some resources of lineageos. 2. the bank app is not just checking for play integrity or "root", he may have checked other things, such as files on your device, or your ip, etc.
> > I googled "payzapp" and found the following: https://www.desidime.com/discussions/rooted-phone-users-do-not-update-payzapp
> > Someone mentioned:
> > > mine's not rooted and still shows that error - RIP
> 
> 😃🥳Thanks for the help for the new build yesterday you have posted that helps me to bypass the root or jailbroke message from bank apps.....I using the lineage OS and kernalSU on first time using that installed the kernalSU it shows the root or jailbroke message yesterday I reflash with your new build and nikgapps used instead of mindgapps it's working......today the app is showing in Play Store (payzapp) but play integrity check (MEET_STRONG_INTEGRITY) is failed and in Play Store- device is not certified.....how the app is working I don't know 🤔🤔😅

(MEET_STRONG_INTEGRITY) failure is the expected behavior. Like I said at the beginning, as long as your app is working fine, there's no need to care what the Safetynet check results in.

-------

The device is not certified requires you to submit your device id：
https://www.google.com/android/uncertified/

**Comment by CYBEROG08** [comment]
> > > > Sorry I can't get it
> > > 
> > > 
> > > What I would like to know is how did you get "root" privileges on your android device . For example, magisk,kernelsu...
> > > Generally speaking, flashing lineageos alone will not cause "rooted or jailbreak" of bank apps, I can think of two points: 1, the lineageos system you flashed does not conform to the safe implementation, it may have modified some parts of the app to cause errors, or you modified some resources of lineageos. 2. the bank app is not just checking for play integrity or "root", he may have checked other things, such as files on your device, or your ip, etc.
> > > I googled "payzapp" and found the following: https://www.desidime.com/discussions/rooted-phone-users-do-not-update-payzapp
> > > Someone mentioned:
> > > > mine's not rooted and still shows that error - RIP
> > 
> > 
> > 😃🥳Thanks for the help for the new build yesterday you have posted that helps me to bypass the root or jailbroke message from bank apps.....I using the lineage OS and kernalSU on first time using that installed the kernalSU it shows the root or jailbroke message yesterday I reflash with your new build and nikgapps used instead of mindgapps it's working......today the app is showing in Play Store (payzapp) but play integrity check (MEET_STRONG_INTEGRITY) is failed and in Play Store- device is not certified.....how the app is working I don't know 🤔🤔😅
> 
> (MEET_STRONG_INTEGRITY) failure is the expected behavior. Like I said at the beginning, as long as your app is working fine, there's no need to care what the Safetynet check results in.
> 
> The device is not certified requires you to submit your device id： https://www.google.com/android/uncertified/


Actually I registered using with my device ID yesterday

**Comment by CYBEROG08** [comment]
> > > > Sorry I can't get it
> > > 
> > > 
> > > What I would like to know is how did you get "root" privileges on your android device . For example, magisk,kernelsu...
> > > Generally speaking, flashing lineageos alone will not cause "rooted or jailbreak" of bank apps, I can think of two points: 1, the lineageos system you flashed does not conform to the safe implementation, it may have modified some parts of the app to cause errors, or you modified some resources of lineageos. 2. the bank app is not just checking for play integrity or "root", he may have checked other things, such as files on your device, or your ip, etc.
> > > I googled "payzapp" and found the following: https://www.desidime.com/discussions/rooted-phone-users-do-not-update-payzapp
> > > Someone mentioned:
> > > > mine's not rooted and still shows that error - RIP
> > 
> > 
> > 😃🥳Thanks for the help for the new build yesterday you have posted that helps me to bypass the root or jailbroke message from bank apps.....I using the lineage OS and kernalSU on first time using that installed the kernalSU it shows the root or jailbroke message yesterday I reflash with your new build and nikgapps used instead of mindgapps it's working......today the app is showing in Play Store (payzapp) but play integrity check (MEET_STRONG_INTEGRITY) is failed and in Play Store- device is not certified.....how the app is working I don't know 🤔🤔😅
> 
> (MEET_STRONG_INTEGRITY) failure is the expected behavior. Like I said at the beginning, as long as your app is working fine, there's no need to care what the Safetynet check results in.
> 
> The device is not certified requires you to submit your device id： https://www.google.com/android/uncertified/


I did it yesterday itself......2hrs before I cleared the cache and storage for play Store and play service now it shows 'device is certified'
Thanks 👍
